name: weather_app
version: 1.0.0+1
publish_to: non
description: A new Flutter project
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  auto_route: ^7.5.0
  awesome_dio_interceptor: ^1.0.0
  bloc: ^8.0.3
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.3.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  pubspec_dependency_sorter: ^1.0.3
  retrofit: ^4.0.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  auto_route_generator: ^7.1.1
  bloc_test: ^9.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.4.1
  injectable_generator: ^2.1.5
  mockito: ^5.0.4
  mocktail: ^0.3.0
  retrofit_generator: ^7.0.2
  very_good_analysis: ^5.0.0
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  generate: true
